"""Back up the list of Claude Code personal skills, not their contents.

Writes `claude-skills/manifest.json` (every entry in ~/.claude/skills with its
source) and `claude-skills/skill-lock.json` (a copy of the skills CLI lock file,
which records source repositories, paths, and folder hashes only). Third-party
skill files stay upstream: the manifest says where to reinstall them from.

    python scripts/export-claude-skills.py

Standard library only. Reads nothing outside ~/.claude/skills and ~/.agents.
"""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

HOME = Path.home()
SKILLS = HOME / ".claude" / "skills"
LOCK = HOME / ".agents" / ".skill-lock.json"
OUT = Path(__file__).resolve().parents[1] / "claude-skills"


def gstack_info(root: Path) -> dict:
    def git(*args: str) -> str:
        result = subprocess.run(["git", "-C", str(root), *args], capture_output=True, text=True)
        return result.stdout.strip()

    version = (root / "VERSION").read_text(encoding="utf-8").strip() if (root / "VERSION").exists() else None
    return {"repo": git("remote", "get-url", "origin"), "commit": git("rev-parse", "HEAD"), "version": version}


def classify(entry: Path, lock: dict, gstack: dict) -> dict:
    name = entry.name
    if entry.is_symlink():
        target = os.readlink(entry).removeprefix("\\\\?\\")  # Windows extended-path prefix
        return {"name": name, "source": "local-symlink", "target": target}
    if name in lock:
        info = lock[name]
        return {"name": name, "source": "skills-cli", "repo": info.get("source"),
                "skill_path": info.get("skillPath")}
    if name == "gstack":
        return {"name": name, "source": "gstack", **gstack}
    if name.startswith(("gstack-", "_gstack")):
        return {"name": name, "source": "gstack-setup", "note": "generated by gstack ./setup"}
    if name == "synced":
        return {"name": name, "source": "claude-account-sync",
                "note": "synced from claude.ai for the signed-in account; restored by signing in, not from files"}
    return {"name": name, "source": "unknown"}


def main() -> int:
    lock_data = json.loads(LOCK.read_text(encoding="utf-8")) if LOCK.exists() else {"skills": {}}
    gstack = gstack_info(SKILLS / "gstack") if (SKILLS / "gstack" / ".git").exists() else {}
    entries = sorted((p for p in SKILLS.iterdir() if p.is_dir() or p.is_symlink()), key=lambda p: p.name)
    skills = [classify(p, lock_data.get("skills", {}), gstack) for p in entries]
    counts: dict = {}
    for skill in skills:
        counts[skill["source"]] = counts.get(skill["source"], 0) + 1
    OUT.mkdir(exist_ok=True)
    manifest = {"schema_version": 1, "skills_dir": "~/.claude/skills", "counts": counts,
                "gstack": gstack, "skills": skills}
    (OUT / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if LOCK.exists():
        (OUT / "skill-lock.json").write_text(json.dumps(lock_data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"exported {len(skills)} skills: {counts}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
